# This is a basic workflow to help you get started with Actions

name: Example Workflow

# Controls when the action will run. 
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Pull request to NJinius. This will simply check if the site still builds
  jobs:
    example-job:
      name: Example Job
      runs-on: ubuntu-latest
      steps:
        - name: Run my test script
        - run: |
            python .tutorial-code-samples/src/my-test-script.py
                
               
              
          
        
